function(devel_target_check_warning TARGET)
  cmake_parse_arguments(ARG "" "" "FLAGS;MSVC_FLAGS" ${ARGN})
  if(MSVC)
    target_compile_options(${TARGET} PRIVATE /WX /permissive- /W4 /w14640 /EHsc ${ARG_MSVC_FLAGS})
  else()
    target_compile_options(${TARGET} PRIVATE -Werror -Wall -Wextra -Wnon-virtual-dtor -Wpedantic ${ARG_FLAGS})
  endif()
endfunction()
